### ISSUE TITLE
ASCII Code for the string

### ISSUE THREAD

**Issue by DVB7781** [DVB7781/DV-Hacktoberfest#1]
### *Description*

Write a Java Program to Take a String from the user and output ASCII Code of each character in a string.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/DVB7781/DV-Hacktoberfest/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (DVB7781)

**Comment by dasanianand** [comment]
@DVB7781 i want to work on this issue
