### ISSUE TITLE
count_letter

### ISSUE THREAD

**Issue by DVB7781** [DVB7781/DV-Hacktoberfest#11]
### Description

Write a Java Program to Calculate the occurrence of each letters in the array.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/DVB7781/DV-Hacktoberfest/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (DVB7781)

**Comment by dasanianand** [comment]
@DVB7781 I want to work on this issue 

Kindly assign this issue to me :)
