### ISSUE TITLE
bool_example

### ISSUE THREAD

**Issue by DVB7781** [DVB7781/DV-Hacktoberfest#12]
### Description

Write a Java Program to Demonstrate boolean in Java

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/DVB7781/DV-Hacktoberfest/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (DVB7781)

**Comment by mbakrol** [comment]
@DVB7781 assign this to me
