### ISSUE TITLE
area_rectangle

### ISSUE THREAD

**Issue by DVB7781** [DVB7781/DV-Hacktoberfest#3]
### Description

Write a Java Program to calculate area of rectangle by taking data with use of various functions.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/DVB7781/DV-Hacktoberfest/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (DVB7781)

**Comment by Onkar627** [comment]
@DVB7781 I would like to work on this issue.
