### ISSUE TITLE
array_2D

### ISSUE THREAD

**Issue by DVB7781** [DVB7781/DV-Hacktoberfest#5]
### Description

program to Demonstrate Multi-Dimension Arrays in Java

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/DVB7781/DV-Hacktoberfest/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (DVB7781)

**Comment by Krupali-Tandel** [comment]
@DVB7781  I want to work on this issue
